"""
Convert 3D model from .obj format to .wrl with colors
"""

from __future__ import annotations

# Global imports
import logging
import re
import textwrap
from typing import Optional

# Local imports
from ..easyeda.parameters_easyeda import Ee3dModel
from .parameters_kicad_footprint import Ki3dModel, Ki3dModelBase

VRML_HEADER = """#VRML V2.0 utf8
# 3D model generated by easyeda2kicad.py (https://github.com/uPesy/easyeda2kicad.py)
"""


def get_materials(obj_data: str) -> dict:
    material_regex = "newmtl .*?endmtl"
    matchs = re.findall(pattern=material_regex, string=obj_data, flags=re.DOTALL)

    materials = {}
    for match in matchs:
        material = {}
        material_id = None
        for value in match.splitlines():
            if value.startswith("newmtl"):
                material_id = value.split()[1]
            elif value.startswith("Ka"):
                material["ambient_color"] = value.split()[1:]
            elif value.startswith("Kd"):
                material["diffuse_color"] = value.split()[1:]
            elif value.startswith("Ks"):
                material["specular_color"] = value.split()[1:]
            elif value.startswith("d"):
                # This isn't exactly the same as transparency, is dissolve
                # I.e. part C115366 (SW-TH_SPEF110100) has d=1, and isn't transparent
                material["transparency"] = value.split()[1]

        if material_id is not None:
            materials[material_id] = material
    return materials


def get_vertices(
    obj_data: str,
    offset_x: float = 0.0,
    offset_y: float = 0.0,
    offset_z: float = 0.0,
) -> list:
    vertices_regex = "v (.*?)\n"
    matchs = re.findall(pattern=vertices_regex, string=obj_data, flags=re.DOTALL)

    return [
        " ".join([
            str(round((float(coords[0]) + offset_x) / 2.54, 4)),
            str(round((float(coords[1]) + offset_y) / 2.54, 4)),
            str(round((float(coords[2]) + offset_z) / 2.54, 4)),
        ])
        for vertice in matchs
        for coords in [vertice.split()]
    ]


def _get_obj_bbox(raw_obj: str) -> tuple:
    """Returns ((x_min, x_max), (y_min, y_max), (z_min, z_max)) from OBJ vertices."""
    x_vals, y_vals, z_vals = [], [], []
    for match in re.finditer(
        r"^v\s+([\d.e+-]+)\s+([\d.e+-]+)\s+([\d.e+-]+)", raw_obj, re.MULTILINE
    ):
        x_vals.append(float(match.group(1)))
        y_vals.append(float(match.group(2)))
        z_vals.append(float(match.group(3)))

    if not x_vals:
        return (0.0, 0.0), (0.0, 0.0), (0.0, 0.0)

    return (
        (min(x_vals), max(x_vals)),
        (min(y_vals), max(y_vals)),
        (min(z_vals), max(z_vals)),
    )


def generate_wrl_model(model_3d: Ee3dModel, fp_type: str = "") -> Ki3dModel:
    if not model_3d.raw_obj:
        return Ki3dModel(
            translation=Ki3dModelBase(),
            rotation=Ki3dModelBase(),
            name=model_3d.name,
            raw_wrl=None,
        )

    materials = get_materials(obj_data=model_3d.raw_obj)

    # For SMD parts: center XY on (0,0) and shift Z so bottom sits at z=0
    offset_x, offset_y, offset_z = 0.0, 0.0, 0.0
    if fp_type == "smd":
        (x_min, x_max), (y_min, y_max), (z_min, _z_max) = _get_obj_bbox(model_3d.raw_obj)
        offset_x = -(x_min + x_max) / 2.0
        offset_y = -(y_min + y_max) / 2.0
        offset_z = -z_min
        logging.debug(
            f"3D SMD centering offset: "
            f"X={offset_x:.2f} Y={offset_y:.2f} Z={offset_z:.2f}"
        )

    vertices = get_vertices(
        obj_data=model_3d.raw_obj,
        offset_x=offset_x,
        offset_y=offset_y,
        offset_z=offset_z,
    )

    raw_wrl = VRML_HEADER
    shapes = model_3d.raw_obj.split("usemtl")[1:]
    for shape in shapes:
        lines = shape.splitlines()
        material = materials[lines[0].replace(" ", "")]
        index_counter = 0
        link_dict = {}
        coord_index = []
        points = []
        for line in lines[1:]:
            if len(line) > 0:
                face = [int(index) for index in line.replace("//", "").split()[1:]]
                face_index = []
                for index in face:
                    if index not in link_dict:
                        link_dict[index] = index_counter
                        face_index.append(str(index_counter))
                        points.append(vertices[index - 1])
                        index_counter += 1
                    else:
                        face_index.append(str(link_dict[index]))
                face_index.append("-1")
                coord_index.append(",".join(face_index) + ",")
        points.insert(-1, points[-1])

        shape_str = textwrap.dedent(
            f"""
            Shape{{
                appearance Appearance {{
                    material  Material 	{{
                        diffuseColor {" ".join(material["diffuse_color"])}
                        specularColor {" ".join(material["specular_color"])}
                        ambientIntensity 0.2
                        transparency 0
                        shininess 0.5
                    }}
                }}
                geometry IndexedFaceSet {{
                    ccw TRUE
                    solid FALSE
                    coord DEF co Coordinate {{
                        point [
                            {(", ").join(points)}
                        ]
                    }}
                    coordIndex [
                        {"".join(coord_index)}
                    ]
                }}
            }}"""
        )

        raw_wrl += shape_str

    return Ki3dModel(
        translation=Ki3dModelBase(),
        rotation=Ki3dModelBase(),
        name=model_3d.name,
        raw_wrl=raw_wrl,
    )


def _log_obj_bbox(raw_obj: str) -> None:
    """Log the OBJ vertex bounding box at DEBUG level."""
    x_vals, y_vals, z_vals = [], [], []
    for match in re.finditer(
        r"^v\s+([\d.e+-]+)\s+([\d.e+-]+)\s+([\d.e+-]+)", raw_obj, re.MULTILINE
    ):
        x_vals.append(float(match.group(1)))
        y_vals.append(float(match.group(2)))
        z_vals.append(float(match.group(3)))

    if not x_vals:
        logging.debug("3D OBJ: no vertices found")
        return

    logging.debug(
        "3D OBJ bbox: "
        f"X [{min(x_vals):.2f} .. {max(x_vals):.2f}] "
        f"Y [{min(y_vals):.2f} .. {max(y_vals):.2f}] "
        f"Z [{min(z_vals):.2f} .. {max(z_vals):.2f}]"
    )


class Exporter3dModelKicad:
    def __init__(self, model_3d: Optional[Ee3dModel], fp_type: str = ""):
        self.input = model_3d
        self.fp_type = fp_type
        if model_3d and model_3d.raw_obj:
            _log_obj_bbox(model_3d.raw_obj)
        self.output = (
            generate_wrl_model(model_3d=model_3d, fp_type=fp_type)
            if model_3d and model_3d.raw_obj
            else None
        )
        self.output_step = model_3d.step if model_3d else None

    def export(self, lib_path: str) -> None:
        if self.output and self.output.raw_wrl:
            with open(
                file=f"{lib_path}.3dshapes/{self.output.name}.wrl",
                mode="w",
                encoding="utf-8",
            ) as my_lib:
                my_lib.write(self.output.raw_wrl)
        if self.output_step and self.output:
            with open(
                file=f"{lib_path}.3dshapes/{self.output.name}.step",
                mode="wb",
            ) as my_lib:
                my_lib.write(self.output_step)
